---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: survival-paper
  name: survival-paper
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: survival-paper
  replicas: 1
  revisionHistoryLimit: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: survival-paper
  template:
    metadata:
      labels:
        app: survival-paper
    spec:
      containers:
        - name: survival-paper
          image: itzg/minecraft-server
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Gi" # Adjust based on your server's requirements
              cpu: 5000m       # Adjust based on your server's requirements
            limits:
              memory: "18Gi" # Adjust based on your server's requirements
              cpu: 7000m       # Adjust based on your server's requirements
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.20.6"
            - name: DIFFICULTY
              value: "HARD"
            - name: MEMORY
              value: "16G"
            - name: "SIMULATION_DISTANCE"
              value: "16"
            - name: "VIEW_DISTANCE"
              value: "32"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: DEBUG
              value: "FALSE"
            - name: MAX_PLAYERS
              value: "80"
            - name: PLUGINS
              value: |
                https://download.luckperms.net/1543/bukkit/loader/LuckPerms-Bukkit-5.4.130.jar
                https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+93-3a6fdd9.jar
                https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXChat-2.21.0-dev+93-3a6fdd9.jar
                https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXSpawn-2.21.0-dev+93-3a6fdd9.jar
                https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
                https://dev.bukkit.org/projects/worldguard/files/latest
                https://dev.bukkit.org/projects/grief-prevention/files/latest
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.10.2/PAPER/ViaVersion-4.10.2.jar
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/4.10.2/PAPER/ViaBackwards-4.10.2.jar
                https://dev.bukkit.org/projects/thizzyz-tree-feller/files/latest
                https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.0.12/SkinsRestorer.jar
                https://hangarcdn.papermc.io/plugins/HelpChat/PlaceholderAPI/versions/2.11.6/PAPER/PlaceholderAPI-2.11.6.jar
                https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.1.2/PAPER/AuraSkills-2.1.2.jar
                https://github.com/Qveshn/LightAPI/releases/download/3.5.2/LightAPI-fork-3.5.2.jar
            - name: SPIGET_RESOURCES
              value: |
                74188
                40313
                59773
            - name: MODRINTH_PROJECTS
              value: |
                veinminer:nxn7XLQe
                worldedit:VaMk0SQH
                quests.classic:9aib87oe
                discordsrv:mr2CijyC
                papiproxybridge:RXXUN9SA
                dynmap:CeFY2xAD
                chunky:ZrmnYk7q
                invsee++:GoiUaKNC
            - name: MODRINTH_DOWNLOAD_DEPENDENCIES
              value: "required"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /data
              name: data
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
                - --host
                - localhost
                - --port
                - "25565"
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: survival-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: iscsi
        resources:
          requests:
            storage: 1000Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: survival-paper
  name: survival-paper
  namespace: minecraft
spec:
  ports:
    - name: game
      port: 25565
      targetPort: 25565
      nodePort: 30065
    - name: web 
      port: 8123
      targetPort: 8123
      nodePort: 30123
  selector:
    app: survival-paper
  type: NodePort