apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
spec:
  storageClassName: iscsi
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal:
    iqn:
    lun: 0
    fsType: 'ext4'
    readOnly: false