apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  storageClassName: iscsi
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 
    iqn: 
    lun: 0
    fsType: 'ext4'
    readOnly: false