apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  storageClassName: iscsi
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: <IQN_TARGET_IP>
    iqn: <YOUR_IQN>
    lun: 0
    fsType: 'ext4'
    readOnly: false