apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-db-pv

spec:
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  nfs: 
    path:  /mnt/CH-NAS1/kubeShare/test
    server: truenas
