apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv

spec:
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 25Gi
  nfs: 
    path:  /mnt/kubeShare/test
    server: truenas
