apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: database

spec:
  storageClassName: iscsi
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 250Gi
