apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mc-java
  name: mc-java
  namespace: minecraft
spec:
  replicas: 1
  serviceName: mc-java
  selector:
    matchLabels:
      app: mc-java
  template:
    metadata:
      labels:
        app: mc-java
    spec:
      containers:
        - name: mc-java
          image: itzg/minecraft-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - mountPath: /data
              name: data
          nodeSelector:
            cputype: amd64
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
                - --host
                - localhost
                - --port
                - "25565"
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mc-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: iscsi
        resources:
          requests:
            storage: 1Gi
        nodeSelector:
          cputype: amd64
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mc-java
  name: mc-java
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30065
  selector:
    app: mc-java
  type: NodePort