apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mc-java
  name: mc-java
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: mc-java
  replicas: 1
  revisionHistoryLimit: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: mc-java
  template:
    metadata:
      labels:
        app: mc-java
    spec:
      containers:
        - name: mc-java
          image: itzg/minecraft-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.20.4"
            - name: DIFFICULTY
              value: "HARD"
            - name: MEMORY
              value: "12G"
            - name: "SIMULATION_DISTANCE"
              value: "16"
            - name: "VIEW_DISTANCE"
              value: "28"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: PLUGINS
              value: |
                https://download.luckperms.net/1540/bukkit/loader/LuckPerms-Bukkit-5.4.127.jar
                https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
                https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXChat-2.20.1.jar
                https://github.com/KaspianDev/AntiPopup/releases/download/bb3448e/AntiPopup-7.3-HOTFIX.jar
                https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXSpawn-2.20.1.jar
                https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
                https://dev.bukkit.org/projects/worldguard/files/4675318/download
                https://dev.bukkit.org/projects/grief-prevention/files/5301423/download
                https://hangarcdn.papermc.io/plugins/pop4959/Chunky/versions/1.4.10/PAPER/Chunky-1.4.10.jar
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/4.10.1/PAPER/ViaVersion-4.10.1.jar
                https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/4.10.1/PAPER/ViaBackwards-4.10.1.jar
                https://github.com/TrueMB/DiscordNotify/releases/download/3.3.5/DiscordNotify-3.3.5.jar
                https://github.com/SkinsRestorer/SkinsRestorer/releases/download/15.0.12/SkinsRestorer.jar
                https://hangarcdn.papermc.io/plugins/HelpChat/PlaceholderAPI/versions/2.11.5/PAPER/PlaceholderAPI-2.11.5.jar
                https://hangarcdn.papermc.io/plugins/Archy/AuraSkills/versions/2.0.9/PAPER/AuraSkills-2.0.9.jar
            - name: SPIGET_RESOURCES
              value: |
                78766
                74188
                40313
            - name: MODRINTH_PROJECTS
              value: |
                veinminer:aEIcjoEO
                worldedit:JzCMkGax
            - name: MODRINTH_DOWNLOAD_DEPENDENCIES
              value: "required"
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /data
              name: data
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status
                - --host
                - localhost
                - --port
                - "25565"
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mc-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: iscsi
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mc-java
  name: mc-java
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30065
  selector:
    app: mc-java
  type: NodePort