apiVersion: v1
kind: PersistentVolume
metadata:
  name: mc-pv
  namespace: default
spec:
  storageClassName: iscsi
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: <IP_OR_HOST_OF_IQN>
    iqn: <IQN>
    lun: 0
    fsType: 'ext4'
    readOnly: false