apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-storage
  namespace: default
spec:
  storageClassName: iscsi
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 
    iqn:  
    lun: 0
    fsType: 'ext4'
    readOnly: false