name: Minecraft Deployment

on:
  push:
    branches:
      - main

env: 
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  MC_NODE_PORT: ${{ secrets.MC_NODE_PORT }} 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Minecraft Server
        uses: actions-hub/kubectl@master
        with:
          args: apply -f k8s-apps/minecraft/deployment.yaml